const phishingKeywords = {
  urgency: [
    "urgent",
    "immediately",
    "verify now",
    "act now",
    "warning",
    "suspended",
    "act immediately",
    "deadline",
    "expires today",
    "final notice",
    "last warning",
    "response required",
    "important notice",
    "critical alert",
    "within 24 hours",
    "within 48 hours",
    "take action now",
    "do not ignore",
    "failure to comply",
    "account closure",
    "service interruption"
  ],

  banking: [
    "bank",
    "banking",
    "account",
    "checking account",
    "savings account",
    "payment",
    "credit card",
    "debit card",
    "wire transfer",
    "transaction",
    "fund transfer",
    "bank statement",
    "bank alert",
    "bank security",
    "account verification",
    "verify account",
    "online banking",
    "financial institution",
    "balance",
    "unauthorized transaction",
    "invoice",
    "accounts payable",
    "vendor payment",
    "supplier payment",
    "remittance",
    "purchase order",
    "outstanding balance"
  ],

  credentials: [
    "password",
    "otp",
    "username",
    "login",
    "log in",
    "signin",
    "sign in",
    "verification code",
    "credentials",
    "credential",
    "reset password",
    "change password",
    "confirm password",
    "verify password",
    "security code",
    "authentication",
    "identity verification",
    "security question",
    "recover account",
    "2fa",
    "mfa",
    "one time password",
    "two factor authentication"
  ],

  scam: [
    "reward",
    "prize",
    "free",
    "winner",
    "claim now",
    "bonus",
    "cash prize",
    "lottery",
    "gift card",
    "claim reward",
    "claim prize",
    "selected winner",
    "jackpot",
    "sweepstakes",
    "lucky draw",
    "promotion",
    "exclusive offer",
    "special offer",
    "free iphone",
    "free smartphone",
    "free laptop"
  ],

  crypto: [
    "bitcoin",
    "btc",
    "ethereum",
    "eth",
    "crypto",
    "cryptocurrency",
    "wallet",
    "blockchain",
    "token",
    "nft",
    "defi",
    "private key",
    "seed phrase",
    "recovery phrase",
    "coinbase",
    "binance",
    "metamask",
    "trust wallet"
  ],

  delivery: [
    "package",
    "parcel",
    "shipment",
    "delivery",
    "tracking number",
    "courier",
    "failed delivery",
    "delivery attempt",
    "shipping update",
    "dhl",
    "fedex",
    "ups",
    "usps"
  ],

  government: [
    "government",
    "police",
    "court notice",
    "legal action",
    "arrest warrant",
    "immigration",
    "passport office",
    "social security",
    "law enforcement",
    "official notice"
  ],

  tax: [
    "tax refund",
    "refund pending",
    "income tax",
    "tax department",
    "tax return",
    "irs",
    "revenue service",
    "refund available",
    "tax payment"
  ],

  employment: [
    "job offer",
    "work from home",
    "remote job",
    "easy income",
    "earn money",
    "hiring immediately",
    "interview selected",
    "recruitment",
    "employment opportunity",
    "part time work"
  ],

  techSupport: [
    "virus detected",
    "trojan detected",
    "technical support",
    "customer service",
    "help desk",
    "security alert",
    "your computer",
    "device infected",
    "malware detected",
    "system compromised",
    "call support",
    "call immediately"
  ],

  extortion: [
    "i have hacked",
    "i know your password",
    "bitcoin payment",
    "private video",
    "webcam footage",
    "pay within 24 hours",
    "blackmail",
    "extortion"
  ]
};

module.exports = phishingKeywords;